"""
Created by: Abhirup Paul and Robert Newberry | Newberry Lab | University of Texas, Austin
https://www.newberrylab.com/
This code helps trim and clean the MSA file (.A3M) generated by Alphafold2 for use in RibbonFold
"""
def clean_fasta():
    input_file = r"C:\WORK\P.hD\Newberry_Lab\Research\RDPs\RDP_8 (RibbonFold)\test\SYUA_msa.fasta"
    output_file = r"C:\WORK\P.hD\Newberry_Lab\Research\RDPs\RDP_8 (RibbonFold)\test\processed_SYUA_msa.fasta"
    ###Change the folder paths accordingly
    with open(input_file, 'r') as infile, open(output_file, 'w') as outfile:
        for line in infile:
            if line.startswith('>'):
                #Keep only the first word after '>'
                first_word = line.strip().split()[0]
                outfile.write(f"{first_word}\n")
            else:
                outfile.write(line.strip() + "\n")
    print(f"The MSA file has been cleaned and processed successfully.")
clean_fasta()
